[package]
name = "device_query"
version = "0.2.4"
authors = ["ostrosco <ostrosco@fastmail.fm>"]
build = "build.rs"
description = "A basic library for querying keyboard and mouse state on-demand without a window."
homepage = "https://github.com/ostrosco/device_query"
repository = "https://github.com/ostrosco/device_query"
readme = "README.md"
keywords = ["input", "mouse", "keyboard"]
license = "MIT"

[build-dependencies]
pkg-config = "0.3.18"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = {version = "2.18.2", features = ["xlib"] }

[target.'cfg(target_os = "windows")'.dependencies]
user32-sys = "0.2.0"
